// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBik2sHhsXWLdN3VJJo-2d0URCF5IndC4I',
    appId: '1:699345967742:web:b837f959f76de64eefd62f',
    messagingSenderId: '699345967742',
    projectId: 'pharma-x-mobile',
    authDomain: 'pharma-x-mobile.firebaseapp.com',
    storageBucket: 'pharma-x-mobile.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA911rM9IsE8zkIN-p3DozD40VCxRJ52_k',
    appId: '1:699345967742:android:22da26ac095a95fbefd62f',
    messagingSenderId: '699345967742',
    projectId: 'pharma-x-mobile',
    storageBucket: 'pharma-x-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG-heyQT92OWd70p3CGQJVAOp0XhiKbnE',
    appId: '1:699345967742:ios:b62eb6b06766e417efd62f',
    messagingSenderId: '699345967742',
    projectId: 'pharma-x-mobile',
    storageBucket: 'pharma-x-mobile.firebasestorage.app',
    iosBundleId: 'com.example.pharmax',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG-heyQT92OWd70p3CGQJVAOp0XhiKbnE',
    appId: '1:699345967742:ios:b62eb6b06766e417efd62f',
    messagingSenderId: '699345967742',
    projectId: 'pharma-x-mobile',
    storageBucket: 'pharma-x-mobile.firebasestorage.app',
    iosBundleId: 'com.example.pharmax',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBik2sHhsXWLdN3VJJo-2d0URCF5IndC4I',
    appId: '1:699345967742:web:7feb7a41ac5859e5efd62f',
    messagingSenderId: '699345967742',
    projectId: 'pharma-x-mobile',
    authDomain: 'pharma-x-mobile.firebaseapp.com',
    storageBucket: 'pharma-x-mobile.firebasestorage.app',
  );
}
